import type { NextFunction, Request, Response } from 'express';
import { AppError } from '../../utils/app-error.js';
import { createdResponse, successResponse } from '../../utils/response.js';
import * as repo from './website.repo.js';
import { createDomainSchema, createJobSchema, createSiteSchema, domainParams, jobParams, siteIdParams } from './website.validator.js';

type WorkspaceRequest = Request & { user?: { id: string } };
function workspaceId(req: Request) { return String(req.params.workspaceId); }

export async function list(req: Request, res: Response, next: NextFunction) { try { return successResponse(res, 'Website sites loaded', { items: await repo.listSites(workspaceId(req)) }); } catch (error) { next(error); } }
export async function create(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const input = createSiteSchema.parse(req.body); if (input.provider === 'managed' && input.ownershipMode !== 'managed') throw new AppError(400, 'WEBSITE_OWNERSHIP_MODE_INVALID', 'Managed provider sites must use managed ownership'); if (input.provider !== 'managed' && input.ownershipMode !== 'connected') throw new AppError(400, 'WEBSITE_OWNERSHIP_MODE_INVALID', 'WordPress and Webflow sites must use connected ownership'); return createdResponse(res, 'Website site created', await repo.createSite({ workspaceId: workspaceId(req), ...input })); } catch (error) { next(error); } }
export async function addDomain(req: Request, res: Response, next: NextFunction) { try { const params = siteIdParams.parse(req.params); const site = await repo.getSite(params.workspaceId, params.siteId); if (!site) throw new AppError(404, 'WEBSITE_SITE_NOT_FOUND', 'Website site was not found'); return createdResponse(res, 'Domain verification created', await repo.createDomain(params.siteId, createDomainSchema.parse(req.body).hostname)); } catch (error) { next(error); } }
export async function verifyDomain(req: Request, res: Response, next: NextFunction) { try { const params = domainParams.parse(req.params); const site = await repo.getSite(params.workspaceId, params.siteId); if (!site) throw new AppError(404, 'WEBSITE_SITE_NOT_FOUND', 'Website site was not found'); const updated = await repo.markDomainVerified(params.siteId, params.domainId); if (!updated) throw new AppError(404, 'WEBSITE_DOMAIN_NOT_FOUND', 'Website domain was not found'); return successResponse(res, 'Domain verified', await repo.getSite(params.workspaceId, params.siteId)); } catch (error) { next(error); } }
export async function createJob(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const params = siteIdParams.parse(req.params); const site = await repo.getSite(params.workspaceId, params.siteId); if (!site) throw new AppError(404, 'WEBSITE_SITE_NOT_FOUND', 'Website site was not found'); return createdResponse(res, 'Website generation job created', await repo.createJob({ siteId: params.siteId, prompt: createJobSchema.parse(req.body).prompt, createdBy: req.user!.id })); } catch (error) { next(error); } }
export async function getJob(req: Request, res: Response, next: NextFunction) { try { const params = jobParams.parse(req.params); const job = await repo.getJob(params.siteId, params.jobId); if (!job) throw new AppError(404, 'WEBSITE_GENERATION_JOB_NOT_FOUND', 'Website generation job was not found'); return successResponse(res, 'Website generation job loaded', job); } catch (error) { next(error); } }
