-- Admin deletion jobs are de-duplicated while the target `users` row is
-- locked inside the queuing transaction. Do not add an index to
-- background_jobs here: existing production installations can contain a
-- very large historical job table, and a full-table index build would delay
-- an otherwise small, availability-critical deployment.
