import { Router } from 'express';
import { requireWorkspaceEditor, requireWorkspaceMember } from '../../middlewares/workspace.middleware.js';
import { methodNotAllowed } from '../../middlewares/methodNotAllowed.middleware.js';
import { dbRateLimit } from '../../middlewares/rateLimit.middleware.js';
import * as controller from './email.controller.js';

const router = Router({ mergeParams: true });
router.use(requireWorkspaceMember);
const rateLimitMessage = 'Too many email actions were requested. Please wait and try again.';
const connectionLimiter = dbRateLimit({ keyPrefix: 'email-connect', windowMs: 60 * 60 * 1000, limit: 10, message: rateLimitMessage });
const syncLimiter = dbRateLimit({ keyPrefix: 'email-sync', windowMs: 60 * 60 * 1000, limit: 30, message: rateLimitMessage });
const aiDraftLimiter = dbRateLimit({ keyPrefix: 'email-ai-draft', windowMs: 60 * 60 * 1000, limit: 40, message: rateLimitMessage });
const sendLimiter = dbRateLimit({ keyPrefix: 'email-send', windowMs: 60 * 60 * 1000, limit: 100, message: rateLimitMessage });
router.route('/accounts').get(controller.accounts).all(methodNotAllowed);
router.route('/accounts/oauth/start').post(requireWorkspaceEditor, connectionLimiter, controller.startOAuth).all(methodNotAllowed);
router.route('/accounts/imap').post(requireWorkspaceEditor, connectionLimiter, controller.connectImap).all(methodNotAllowed);
router.route('/accounts/:accountId').delete(requireWorkspaceEditor, controller.disconnect).all(methodNotAllowed);
router.route('/accounts/:accountId/sync').post(requireWorkspaceEditor, syncLimiter, controller.startSync).all(methodNotAllowed);
router.route('/accounts/:accountId/sync/:jobId').get(controller.syncJob).all(methodNotAllowed);
router.route('/folders').get(controller.folders).all(methodNotAllowed);
router.route('/threads').get(controller.threads).all(methodNotAllowed);
router.route('/threads/:threadId').get(controller.thread).all(methodNotAllowed);
router.route('/threads/:threadId/ai-draft').post(requireWorkspaceEditor, aiDraftLimiter, controller.aiDraft).all(methodNotAllowed);
router.route('/messages/:messageId').patch(requireWorkspaceEditor, controller.updateMessage).all(methodNotAllowed);
router.route('/drafts').get(controller.drafts).post(requireWorkspaceEditor, controller.createDraft).all(methodNotAllowed);
router.route('/drafts/:draftId').patch(requireWorkspaceEditor, controller.updateDraft).all(methodNotAllowed);
router.route('/drafts/:draftId/send').post(requireWorkspaceEditor, sendLimiter, controller.sendDraft).all(methodNotAllowed);
router.route('/automations').get(controller.rules).post(requireWorkspaceEditor, controller.createRule).all(methodNotAllowed);
router.route('/automations/:ruleId').patch(requireWorkspaceEditor, controller.updateRule).delete(requireWorkspaceEditor, controller.deleteRule).all(methodNotAllowed);
export default router;
