import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { before, after, describe, it, mock } from 'node:test';
import { readdir, readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

process.env.NODE_ENV='test'; process.env.DATABASE_URL='postgres://test:test@127.0.0.1:1/omni_tests'; process.env.JWT_SECRET='omnichannel-tests-secret-0123456789';
const { pool }=await import('../src/db/pool.js');
const repo=await import('../src/modules/omnichannel/omnichannel.repo.js');
const service=await import('../src/modules/omnichannel/omnichannel.service.js');
const { UnifyPortAdapter }=await import('../src/modules/provider-control/unifyport.adapter.js');
const db=new PGlite();
before(async()=>{for(const file of (await readdir('src/database/migrations')).filter(name=>name.endsWith('.sql')).sort()) await db.exec(await readFile(`src/database/migrations/${file}`,'utf8')); const execute=async(sql:string,values:unknown[]=[])=>{const result=await db.query(sql,values);return {rows:result.rows,rowCount:result.affectedRows??result.rows.length};}; mock.method(pool,'query',execute as never); mock.method(pool,'connect',(async()=>({query:execute,release(){}})) as never);});
after(async()=>{mock.restoreAll();await pool.end();await db.close();});

async function fixture(){const suffix=crypto.randomUUID(); const aUser=(await db.query<{id:string}>(`INSERT INTO users(email,password_hash,role,verified_at) VALUES($1,'hash','user',NOW()) RETURNING id`,[`${crypto.randomUUID()}@test.local`])).rows[0]!.id; const bUser=(await db.query<{id:string}>(`INSERT INTO users(email,password_hash,role,verified_at) VALUES($1,'hash','user',NOW()) RETURNING id`,[`${crypto.randomUUID()}@test.local`])).rows[0]!.id; const a=(await db.query<{id:string}>(`INSERT INTO workspaces(name,created_by) VALUES('Omni A',$1) RETURNING id`,[aUser])).rows[0]!.id; const b=(await db.query<{id:string}>(`INSERT INTO workspaces(name,created_by) VALUES('Omni B',$1) RETURNING id`,[bUser])).rows[0]!.id; await db.query(`INSERT INTO workspace_members(workspace_id,user_id,role) VALUES($1,$2,'owner'),($3,$4,'owner')`,[a,aUser,b,bUser]); const channel=(await db.query<{id:string}>(`SELECT id FROM omni_channels WHERE channel_type='WEBSITE_CHAT'`)).rows[0]!.id; const ia=(await db.query<{id:string}>(`INSERT INTO omni_channel_identities(channel_id,workspace_id,identity_type,external_identity_id,display_name,status) VALUES($1,$2,'WEBSITE',$3,'A','ACTIVE') RETURNING id`,[channel,a,`a-${suffix}`])).rows[0]!.id; const ib=(await db.query<{id:string}>(`INSERT INTO omni_channel_identities(channel_id,workspace_id,identity_type,external_identity_id,display_name,status) VALUES($1,$2,'WEBSITE',$3,'B','ACTIVE') RETURNING id`,[channel,b,`b-${suffix}`])).rows[0]!.id; const ca=await repo.createConversation({workspaceId:a,channelId:channel,channelIdentityId:ia}); const cb=await repo.createConversation({workspaceId:b,channelId:channel,channelIdentityId:ib}); return {a,b,ia,ib,ca,cb};}

describe('OmniChannel tenant and idempotency guarantees',()=>{
 it('lists and opens only the requested workspace',async()=>{const f=await fixture();assert.equal((await repo.listConversations(f.a,{page:1,limit:50})).items.length,1);assert.equal(await repo.getConversation(f.a,f.cb.id),null);});
 it('keeps inbound retries idempotent and internal notes non-external',async()=>{const f=await fixture();const first=await repo.createMessage({workspaceId:f.a,conversationId:f.ca.id,channelId:f.ca.channelId,channelIdentityId:f.ca.channelIdentityId,direction:'INBOUND',senderType:'BUYER',messageType:'TEXT',text:'hello',clientMessageId:'browser-1'});const second=await repo.createMessage({workspaceId:f.a,conversationId:f.ca.id,channelId:f.ca.channelId,channelIdentityId:f.ca.channelIdentityId,direction:'INBOUND',senderType:'BUYER',messageType:'TEXT',text:'hello',clientMessageId:'browser-1'});assert.equal(first.id,second.id);const note=await repo.createMessage({workspaceId:f.a,conversationId:f.ca.id,channelId:f.ca.channelId,channelIdentityId:f.ca.channelIdentityId,direction:'INTERNAL',senderType:'USER',messageType:'INTERNAL_NOTE',text:'private'});assert.equal(note.messageType,'INTERNAL_NOTE');assert.equal(note.direction,'INTERNAL');});
 it('blocks unknown public website-chat widgets instead of creating a session',async()=>{await assert.rejects(()=>service.publicSession({widgetId:'unknown-widget-id'}),(error:any)=>error?.code==='NOT_FOUND'&&error?.status===404);});
 it('hides retired WeChat and SMS channels while preserving admin detail access',async()=>{const f=await fixture();const channels=await repo.listChannels('__ADMIN__');assert.equal(channels.some((channel:any)=>channel.channelType==='WECHAT'||channel.channelType==='SMS'),false);const detail=await repo.getAdminConversation(f.cb.id);assert.equal(detail?.conversation.workspaceId,f.b);});
 it('does not expose shared channel identities to an unrelated workspace',async()=>{const f=await fixture();const channel=(await db.query<{id:string}>(`SELECT id FROM omni_channels WHERE channel_type='WHATSAPP'`)).rows[0]!.id;await db.query(`INSERT INTO omni_channel_identities(channel_id,workspace_id,identity_type,external_identity_id,display_name,status) VALUES($1,NULL,'SHARED','shared-${crypto.randomUUID()}','Shared Lulu','ACTIVE')`,[channel]);const channels=await repo.listChannels(f.a);const whatsapp=channels.find((item:any)=>item.channelType==='WHATSAPP');assert.equal(whatsapp?.identities.some((identity:any)=>identity.workspaceId===null),false);});
 it('sanitizes public history and never returns internal notes',async()=>{const f=await fixture();const inbound=await repo.createMessage({workspaceId:f.a,conversationId:f.ca.id,channelId:f.ca.channelId,channelIdentityId:f.ca.channelIdentityId,direction:'INBOUND',senderType:'BUYER',messageType:'TEXT',text:'public'});await repo.createMessage({workspaceId:f.a,conversationId:f.ca.id,channelId:f.ca.channelId,channelIdentityId:f.ca.channelIdentityId,direction:'INTERNAL',senderType:'USER',messageType:'INTERNAL_NOTE',text:'secret'});const result=await repo.getPublicConversation(f.a,f.ca.id);assert.equal((result?.conversation as any).workspaceId,undefined);assert.deepEqual(result?.messages.map((message:any)=>message.id),[inbound.id]);assert.equal((result?.messages[0] as any).workspaceId,undefined);});
 it('never reassigns a Twilio sender between workspaces',async()=>{const f=await fixture();const sender=`whatsapp:+1555${crypto.randomInt(1000000,9999999)}`;const first=await repo.registerTwilioIdentity({workspaceId:f.a,channelType:'WHATSAPP',address:sender,displayName:'Workspace A'});assert.equal(first?.workspace_id,f.a);const conflicting=await repo.registerTwilioIdentity({workspaceId:f.b,channelType:'WHATSAPP',address:sender,displayName:'Workspace B'});assert.equal(conflicting,null);const stored=(await db.query<{workspaceId:string;displayName:string}>(`SELECT workspace_id AS "workspaceId",display_name AS "displayName" FROM omni_channel_identities WHERE id=$1`,[first!.id])).rows[0];assert.equal(stored?.workspaceId,f.a);assert.equal(stored?.displayName,'Workspace A');});
 it('routes Twilio retries once and keeps the conversation tenant-scoped',async()=>{const f=await fixture();const sender=`whatsapp:+1666${crypto.randomInt(1000000,9999999)}`;await repo.registerTwilioIdentity({workspaceId:f.a,channelType:'WHATSAPP',address:sender,displayName:'Workspace A'});const input={messageSid:`SM${crypto.randomBytes(16).toString('hex')}`,from:'whatsapp:+491701234567',to:sender,body:'Hello Lulu',messageType:'TEXT',metadata:{NumMedia:'0'}};const first=await repo.ingestTwilioInbound(input);const retry=await repo.ingestTwilioInbound(input);assert.equal(first.routed,true);assert.equal(retry.routed,true);assert.equal('duplicate' in retry&&retry.duplicate,true);assert.equal('workspaceId' in first&&first.workspaceId,f.a);assert.equal('message' in first&&'message' in retry&&first.message.id,retry.message.id);assert.equal(await repo.getConversation(f.b,'conversationId' in first?first.conversationId:''),null);});
 it('normalizes UnifyPort WhatsApp webhooks and queues exactly one autonomous reply job',async()=>{const f=await fixture();const accountId=`acc_${crypto.randomBytes(8).toString('hex')}`;await repo.registerUnifyPortIdentity({workspaceId:f.a,accountId,displayName:'Workspace A WhatsApp'});const eventId=`evt_${crypto.randomBytes(8).toString('hex')}`;const messageId=`msg_${crypto.randomBytes(8).toString('hex')}`;const payload={id:eventId,type:'message.received',account_id:accountId,data:{message:{id:messageId,type:'text',text:'Hello from WhatsApp',conversation:{id:'491701234567@s.whatsapp.net'},sender:{id:'491701234567@s.whatsapp.net',name:'Buyer'}}}};const adapter=new UnifyPortAdapter();const first=await adapter.handleWebhook({eventType:'message.received',externalEventId:eventId,metadata:{eventPayload:payload}});const retry=await adapter.handleWebhook({eventType:'message.received',externalEventId:eventId,metadata:{eventPayload:payload}});assert.equal(first.handled,true);assert.equal(retry.handled,true);const conversation=(await repo.listConversations(f.a,{page:1,limit:50})).items.find(item=>item.subject==='WhatsApp conversation');assert.ok(conversation);const detail=await repo.getConversation(f.a,conversation!.id);assert.equal(detail?.messages.length,1);assert.equal(detail?.messages[0]?.providerMessageId,messageId);assert.equal((await db.query<{count:string}>(`SELECT count(*)::text AS count FROM omni_ai_reply_jobs WHERE message_id=$1`,[detail!.messages[0]!.id])).rows[0]!.count,'1');});
 it('never reassigns an UnifyPort account between workspaces',async()=>{const f=await fixture();const accountId=`acc_${crypto.randomBytes(8).toString('hex')}`;const first=await repo.registerUnifyPortIdentity({workspaceId:f.a,accountId,displayName:'Workspace A'});const conflicting=await repo.registerUnifyPortIdentity({workspaceId:f.b,accountId,displayName:'Workspace B'});assert.ok(first);assert.equal(conflicting,null);const stored=(await db.query<{workspaceId:string;displayName:string}>(`SELECT workspace_id AS "workspaceId",display_name AS "displayName" FROM omni_channel_identities WHERE id=$1`,[first!.id])).rows[0];assert.equal(stored?.workspaceId,f.a);assert.equal(stored?.displayName,'Workspace A');});
 it('keeps unknown traffic to the shared UnifyPort sender in the explicit routing queue',async()=>{const f=await fixture();const adminId=(await db.query<{id:string}>(`SELECT created_by AS id FROM workspaces WHERE id=$1`,[f.a])).rows[0]!.id;const accountId=`acc_${crypto.randomBytes(8).toString('hex')}`;await repo.registerUnifyPortIdentity({workspaceId:null,accountId,displayName:'Lulu WhatsApp',configuredBy:adminId});const messageId=`msg_${crypto.randomBytes(8).toString('hex')}`;const inbound=await repo.ingestUnifyPortInbound({eventId:`evt_${crypto.randomBytes(8).toString('hex')}`,messageId,accountId,senderId:'491709998887@s.whatsapp.net',conversationId:'491709998887@s.whatsapp.net',body:'Please route me',messageType:'TEXT',metadata:{}});assert.equal(inbound.routed,false);const queue=(await repo.listRoutingQueue()).find((item:any)=>item.provider_message_id===messageId);assert.ok(queue);const resolved=await repo.adminResolveRouting(queue.id,f.a,adminId,'Known customer of workspace A');const detail=await repo.getConversation(f.a,(resolved as any).conversationId);assert.equal(detail?.messages[0]?.clientMessageId,`unifyport:${messageId}`);assert.equal((detail?.participants[0]?.metadata as any)?.provider,'unifyport');});
 it('queues unknown shared-sender traffic and persists it after an explicit tenant routing decision',async()=>{const f=await fixture();const channel=(await db.query<{id:string}>(`SELECT id FROM omni_channels WHERE channel_type='WHATSAPP' AND provider='twilio'`)).rows[0]!.id;const identity=(await db.query<{id:string}>(`INSERT INTO omni_channel_identities(channel_id,workspace_id,identity_type,external_identity_id,display_name,mode,status,capabilities) VALUES($1,NULL,'PLATFORM_SENDER',$2,'Lulu','LULU_MANAGED','ACTIVE','{"messages.send":true}'::jsonb) RETURNING id`,[channel,`whatsapp:+1777${crypto.randomInt(1000000,9999999)}`])).rows[0]!.id;const adminId=(await db.query<{id:string}>(`SELECT created_by AS id FROM workspaces WHERE id=$1`,[f.a])).rows[0]!.id;await db.query(`INSERT INTO twilio_platform_configuration(singleton,admin_whatsapp_identity_id,configured_by) VALUES(TRUE,$1,$2)`,[identity,adminId]);const input={messageSid:`SM${crypto.randomBytes(16).toString('hex')}`,from:'whatsapp:+491709998887',to:(await db.query<{address:string}>(`SELECT external_identity_id AS address FROM omni_channel_identities WHERE id=$1`,[identity])).rows[0]!.address,body:'Please route me',messageType:'TEXT',metadata:{NumMedia:'0'}};const inbound=await repo.ingestTwilioInbound(input);assert.equal(inbound.routed,false);const queue=(await repo.listRoutingQueue()).find((item:any)=>item.provider_message_id===input.messageSid);assert.ok(queue);const resolved=await repo.adminResolveRouting(queue.id,f.a,adminId,'Known customer of workspace A');assert.equal((resolved as any)?.resolved_workspace_id,f.a);const conversation=await repo.getConversation(f.a,(resolved as any).conversationId);assert.equal(conversation?.messages.length,1);assert.equal(conversation?.messages[0]?.textContent,'Please route me');assert.equal((await db.query<{count:string}>(`SELECT count(*)::text AS count FROM omni_ai_reply_jobs WHERE workspace_id=$1 AND message_id=$2`,[f.a,(resolved as any).messageId])).rows[0]!.count,'1');});
});
