import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { before, after, describe, it, mock } from 'node:test';
import { readdir, readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

process.env.NODE_ENV='test'; process.env.DATABASE_URL='postgres://test:test@127.0.0.1:1/omni_tests'; process.env.JWT_SECRET='omnichannel-tests-secret-0123456789';
const { pool }=await import('../src/db/pool.js');
const repo=await import('../src/modules/omnichannel/omnichannel.repo.js');
const db=new PGlite();
before(async()=>{for(const file of (await readdir('src/database/migrations')).filter(name=>name.endsWith('.sql')).sort()) await db.exec(await readFile(`src/database/migrations/${file}`,'utf8')); const execute=async(sql:string,values:unknown[]=[])=>{const result=await db.query(sql,values);return {rows:result.rows,rowCount:result.affectedRows??result.rows.length};}; mock.method(pool,'query',execute as never); mock.method(pool,'connect',(async()=>({query:execute,release(){}})) as never);});
after(async()=>{mock.restoreAll();await pool.end();await db.close();});

async function fixture(){const suffix=crypto.randomUUID(); const aUser=(await db.query<{id:string}>(`INSERT INTO users(email,password_hash,role,verified_at) VALUES($1,'hash','user',NOW()) RETURNING id`,[`${crypto.randomUUID()}@test.local`])).rows[0]!.id; const bUser=(await db.query<{id:string}>(`INSERT INTO users(email,password_hash,role,verified_at) VALUES($1,'hash','user',NOW()) RETURNING id`,[`${crypto.randomUUID()}@test.local`])).rows[0]!.id; const a=(await db.query<{id:string}>(`INSERT INTO workspaces(name,created_by) VALUES('Omni A',$1) RETURNING id`,[aUser])).rows[0]!.id; const b=(await db.query<{id:string}>(`INSERT INTO workspaces(name,created_by) VALUES('Omni B',$1) RETURNING id`,[bUser])).rows[0]!.id; await db.query(`INSERT INTO workspace_members(workspace_id,user_id,role) VALUES($1,$2,'owner'),($3,$4,'owner')`,[a,aUser,b,bUser]); const channel=(await db.query<{id:string}>(`SELECT id FROM omni_channels WHERE channel_type='WEBSITE_CHAT'`)).rows[0]!.id; const ia=(await db.query<{id:string}>(`INSERT INTO omni_channel_identities(channel_id,workspace_id,identity_type,external_identity_id,display_name,status) VALUES($1,$2,'WEBSITE',$3,'A','ACTIVE') RETURNING id`,[channel,a,`a-${suffix}`])).rows[0]!.id; const ib=(await db.query<{id:string}>(`INSERT INTO omni_channel_identities(channel_id,workspace_id,identity_type,external_identity_id,display_name,status) VALUES($1,$2,'WEBSITE',$3,'B','ACTIVE') RETURNING id`,[channel,b,`b-${suffix}`])).rows[0]!.id; const ca=await repo.createConversation({workspaceId:a,channelId:channel,channelIdentityId:ia}); const cb=await repo.createConversation({workspaceId:b,channelId:channel,channelIdentityId:ib}); return {a,b,ia,ib,ca,cb};}

describe('OmniChannel tenant and idempotency guarantees',()=>{
 it('lists and opens only the requested workspace',async()=>{const f=await fixture();assert.equal((await repo.listConversations(f.a,{page:1,limit:50})).items.length,1);assert.equal(await repo.getConversation(f.a,f.cb.id),null);});
 it('keeps inbound retries idempotent and internal notes non-external',async()=>{const f=await fixture();const first=await repo.createMessage({workspaceId:f.a,conversationId:f.ca.id,channelId:f.ca.channelId,channelIdentityId:f.ca.channelIdentityId,direction:'INBOUND',senderType:'BUYER',messageType:'TEXT',text:'hello',clientMessageId:'browser-1'});const second=await repo.createMessage({workspaceId:f.a,conversationId:f.ca.id,channelId:f.ca.channelId,channelIdentityId:f.ca.channelIdentityId,direction:'INBOUND',senderType:'BUYER',messageType:'TEXT',text:'hello',clientMessageId:'browser-1'});assert.equal(first.id,second.id);const note=await repo.createMessage({workspaceId:f.a,conversationId:f.ca.id,channelId:f.ca.channelId,channelIdentityId:f.ca.channelIdentityId,direction:'INTERNAL',senderType:'USER',messageType:'INTERNAL_NOTE',text:'private'});assert.equal(note.messageType,'INTERNAL_NOTE');assert.equal(note.direction,'INTERNAL');});
});
