export const ORDER_STATUSES = [
  'DRAFT',
  'PLACED',
  'CONFIRMED',
  'PROCESSING',
  'PARTIALLY_FULFILLED',
  'FULFILLED',
  'CANCELLED',
] as const;

export type OrderStatus = typeof ORDER_STATUSES[number];

export const FULFILLMENT_STATUSES = [
  'DRAFT',
  'PROCESSING',
  'SHIPPED',
  'DELIVERED',
  'CANCELLED',
] as const;

export type FulfillmentStatus = typeof FULFILLMENT_STATUSES[number];

export type CommerceActorType = 'USER' | 'AI_AGENT' | 'WORKFLOW' | 'SYSTEM' | 'ADMIN';

/**
 * Both HTTP controllers and autonomous workflows enter commerce through the
 * same service contract. actorRef is audit identity, not authorization: callers
 * must authorize the actor before invoking the service.
 */
export type CommerceActor = {
  actorType: CommerceActorType;
  actorRef?: string | null;
  correlationId?: string | null;
  causationId?: string | null;
};

export const COMMERCE_EVENT_TYPES = {
  ORDER_CREATED: DOMAIN_EVENT_TYPES.ORDER_CREATED,
  ORDER_UPDATED: DOMAIN_EVENT_TYPES.ORDER_UPDATED,
  ORDER_PLACED: DOMAIN_EVENT_TYPES.ORDER_PLACED,
  ORDER_CONFIRMED: DOMAIN_EVENT_TYPES.ORDER_CONFIRMED,
  ORDER_PROCESSING: DOMAIN_EVENT_TYPES.ORDER_PROCESSING,
  ORDER_PARTIALLY_FULFILLED: DOMAIN_EVENT_TYPES.ORDER_PARTIALLY_FULFILLED,
  ORDER_FULFILLED: DOMAIN_EVENT_TYPES.ORDER_FULFILLED,
  ORDER_CANCELLED: DOMAIN_EVENT_TYPES.ORDER_CANCELLED,
  INVENTORY_LOCATION_CREATED: DOMAIN_EVENT_TYPES.INVENTORY_LOCATION_CREATED,
  INVENTORY_LOCATION_UPDATED: DOMAIN_EVENT_TYPES.INVENTORY_LOCATION_UPDATED,
  INVENTORY_ADJUSTED: DOMAIN_EVENT_TYPES.INVENTORY_ADJUSTED,
  INVENTORY_RESERVED: DOMAIN_EVENT_TYPES.INVENTORY_RESERVED,
  INVENTORY_RELEASED: DOMAIN_EVENT_TYPES.INVENTORY_RELEASED,
  INVENTORY_FULFILLED: DOMAIN_EVENT_TYPES.INVENTORY_FULFILLED,
  FULFILLMENT_CREATED: DOMAIN_EVENT_TYPES.FULFILLMENT_CREATED,
  FULFILLMENT_PROCESSING: DOMAIN_EVENT_TYPES.FULFILLMENT_PROCESSING,
  FULFILLMENT_SHIPPED: DOMAIN_EVENT_TYPES.FULFILLMENT_SHIPPED,
  FULFILLMENT_DELIVERED: DOMAIN_EVENT_TYPES.FULFILLMENT_DELIVERED,
  FULFILLMENT_CANCELLED: DOMAIN_EVENT_TYPES.FULFILLMENT_CANCELLED,
} as const;

export type CommerceOperationReplay = {
  replayed: boolean;
  resourceId: string | null;
};
import { DOMAIN_EVENT_TYPES } from '../../events/domain-event.types.js';
