import type { NextFunction, Response } from 'express';
import type { AuthedRequest } from '../../middlewares/auth.middleware.js';
import type { WorkspaceRequest } from '../../middlewares/workspace.middleware.js';
import { createdResponse, successResponse } from '../../utils/response.js';
import * as service from './commercial-documents.service.js';
import { acceptQuoteSchema, createInvoiceSchema, createQuoteSchema, documentParamsSchema, invoiceListQuerySchema, policySchema, publicDocumentParamsSchema, quoteListQuerySchema, quoteRevisionSchema, sendDocumentSchema } from './commercial-documents.validator.js';
import * as repo from './commercial-documents.repo.js';

const userId = (req: { user?: { id: string } }) => { if (!req.user?.id) throw new Error('Authentication is required'); return req.user.id; };

export async function listQuotes(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const p = documentParamsSchema.pick({ workspaceId: true }).parse(req.params); return successResponse(res, 'Quotes loaded', await service.listQuotes(p.workspaceId, userId(req), quoteListQuerySchema.parse(req.query))); } catch (e) { next(e); } }
export async function getQuote(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const p = documentParamsSchema.parse(req.params); return successResponse(res, 'Quote loaded', await service.getQuote(p.workspaceId, userId(req), p.documentId)); } catch (e) { next(e); } }
export async function createQuote(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const p = documentParamsSchema.pick({ workspaceId: true }).parse(req.params); return createdResponse(res, 'Quote created', await service.createQuote(p.workspaceId, userId(req), createQuoteSchema.parse(req.body))); } catch (e) { next(e); } }
export async function reviseQuote(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const p = documentParamsSchema.parse(req.params); return createdResponse(res, 'Quote revision created', await service.reviseQuote(p.workspaceId, userId(req), p.documentId, quoteRevisionSchema.parse(req.body))); } catch (e) { next(e); } }
export async function sendQuote(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const p = documentParamsSchema.parse(req.params); return successResponse(res, 'Quote delivery queued', await service.sendQuote(p.workspaceId, userId(req), p.documentId, sendDocumentSchema.parse(req.body))); } catch (e) { next(e); } }

export async function listInvoices(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const p = documentParamsSchema.pick({ workspaceId: true }).parse(req.params); return successResponse(res, 'Invoices loaded', await service.listInvoices(p.workspaceId, userId(req), invoiceListQuerySchema.parse(req.query))); } catch (e) { next(e); } }
export async function getInvoice(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const p = documentParamsSchema.parse(req.params); return successResponse(res, 'Invoice loaded', await service.getInvoice(p.workspaceId, userId(req), p.documentId)); } catch (e) { next(e); } }
export async function createInvoice(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const p = documentParamsSchema.pick({ workspaceId: true }).parse(req.params); return createdResponse(res, 'Invoice created', await service.createInvoice(p.workspaceId, userId(req), createInvoiceSchema.parse(req.body))); } catch (e) { next(e); } }
export async function issueInvoice(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const p = documentParamsSchema.parse(req.params); return successResponse(res, 'Invoice issued', await service.issueInvoice(p.workspaceId, userId(req), p.documentId)); } catch (e) { next(e); } }
export async function sendInvoice(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const p = documentParamsSchema.parse(req.params); return successResponse(res, 'Invoice delivery queued', await service.sendInvoice(p.workspaceId, userId(req), p.documentId, sendDocumentSchema.parse(req.body))); } catch (e) { next(e); } }

export async function getPolicy(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const p = documentParamsSchema.pick({ workspaceId: true }).parse(req.params); return successResponse(res, 'Commercial policy loaded', await service.getPolicy(p.workspaceId, userId(req))); } catch (e) { next(e); } }
export async function updatePolicy(req: WorkspaceRequest, res: Response, next: NextFunction) { try { const p = documentParamsSchema.pick({ workspaceId: true }).parse(req.params); return successResponse(res, 'Commercial policy updated', await service.updatePolicy(p.workspaceId, userId(req), policySchema.parse(req.body))); } catch (e) { next(e); } }

export async function publicDocument(req: AuthedRequest, res: Response, next: NextFunction) { try { const { token } = publicDocumentParamsSchema.parse(req.params); const document = await service.publicDocument(token); if (!document) return res.status(404).json({ success: false, error: { code: 'DOCUMENT_NOT_FOUND', message: 'This document link is invalid or expired.' } }); return successResponse(res, 'Document loaded', document); } catch (e) { next(e); } }
export async function acceptPublicQuote(req: AuthedRequest, res: Response, next: NextFunction) { try { const { token } = publicDocumentParamsSchema.parse(req.params); const input = acceptQuoteSchema.parse(req.body); return successResponse(res, 'Quote decision recorded', await service.acceptPublicQuote(token, input.decision, input.comment ?? null)); } catch (e) { next(e); } }

export async function adminQuotes(req: AuthedRequest, res: Response, next: NextFunction) { try { return successResponse(res, 'Quotes loaded', await repo.listAllQuotes({ workspaceId: typeof req.query.workspaceId === 'string' ? req.query.workspaceId : undefined, status: typeof req.query.status === 'string' ? req.query.status : undefined, search: typeof req.query.search === 'string' ? req.query.search.slice(0, 200) : undefined, limit: Number(req.query.limit) || 200 })); } catch (e) { next(e); } }
export async function adminInvoices(req: AuthedRequest, res: Response, next: NextFunction) { try { return successResponse(res, 'Invoices loaded', await repo.listAllInvoices({ workspaceId: typeof req.query.workspaceId === 'string' ? req.query.workspaceId : undefined, status: typeof req.query.status === 'string' ? req.query.status : undefined, search: typeof req.query.search === 'string' ? req.query.search.slice(0, 200) : undefined, limit: Number(req.query.limit) || 200 })); } catch (e) { next(e); } }
