import type { NextFunction, Response } from 'express';
import type { WorkspaceRequest } from '../../middlewares/workspace.middleware.js';
import { createdResponse, successResponse } from '../../utils/response.js';
import * as service from './omnichannel.service.js';
import { conversationParamsSchema, listConversationsQuerySchema, noteSchema, sendMessageSchema, updateConversationSchema, websiteChatCreateSchema, publicMessageSchema, publicSessionSchema, workspaceParamsSchema, adminResolveRoutingSchema } from './omnichannel.validator.js';
import type { AuthedRequest } from '../../middlewares/auth.middleware.js';

const uid=(req:{user?:{id:string}})=>{if(!req.user)throw new Error('Authentication is required');return req.user.id;};
export async function list(req:WorkspaceRequest,res:Response,next:NextFunction){try{const p=workspaceParamsSchema.parse(req.params);return successResponse(res,'Conversations loaded',await service.list(p.workspaceId,uid(req),listConversationsQuerySchema.parse(req.query)));}catch(e){next(e);}}
export async function detail(req:WorkspaceRequest,res:Response,next:NextFunction){try{const p=conversationParamsSchema.parse(req.params);return successResponse(res,'Conversation loaded',await service.detail(p.workspaceId,p.conversationId,uid(req)));}catch(e){next(e);}}
export async function send(req:WorkspaceRequest,res:Response,next:NextFunction){try{const p=conversationParamsSchema.parse(req.params);const input=sendMessageSchema.parse(req.body);return createdResponse(res,'Message queued',await service.send(p.workspaceId,p.conversationId,uid(req),input.clientMessageId?{text:input.text,messageType:input.messageType,clientMessageId:input.clientMessageId}:{text:input.text,messageType:input.messageType}));}catch(e){next(e);}}
export async function note(req:WorkspaceRequest,res:Response,next:NextFunction){try{const p=conversationParamsSchema.parse(req.params);return createdResponse(res,'Internal note added',await service.note(p.workspaceId,p.conversationId,uid(req),noteSchema.parse(req.body).text));}catch(e){next(e);}}
export async function update(req:WorkspaceRequest,res:Response,next:NextFunction){try{const p=conversationParamsSchema.parse(req.params);return successResponse(res,'Conversation updated',await service.update(p.workspaceId,p.conversationId,uid(req),updateConversationSchema.parse(req.body)));}catch(e){next(e);}}
export async function takeOver(req:WorkspaceRequest,res:Response,next:NextFunction){try{const p=conversationParamsSchema.parse(req.params);return successResponse(res,'Conversation taken over',await service.takeOver(p.workspaceId,p.conversationId,uid(req)));}catch(e){next(e);}}
export async function returnToAi(req:WorkspaceRequest,res:Response,next:NextFunction){try{const p=conversationParamsSchema.parse(req.params);const mode=req.body?.mode==='AI_AUTO'?'AI_AUTO':'AI_ASSISTED';return successResponse(res,'Conversation returned to AI',await service.returnToAi(p.workspaceId,p.conversationId,uid(req),mode));}catch(e){next(e);}}
export async function channels(req:WorkspaceRequest,res:Response,next:NextFunction){try{const p=workspaceParamsSchema.parse(req.params);return successResponse(res,'Channels loaded',await service.channels(p.workspaceId,uid(req)));}catch(e){next(e);}}
export async function analytics(req:WorkspaceRequest,res:Response,next:NextFunction){try{const p=workspaceParamsSchema.parse(req.params);return successResponse(res,'OmniChannel analytics loaded',await service.analytics(p.workspaceId,uid(req)));}catch(e){next(e);}}
export async function createWebsite(req:WorkspaceRequest,res:Response,next:NextFunction){try{const p=workspaceParamsSchema.parse(req.params);return createdResponse(res,'Website Chat configured',await service.createWebsite(p.workspaceId,uid(req),websiteChatCreateSchema.parse(req.body)));}catch(e){next(e);}}
export async function publicSession(req:AuthedRequest,res:Response,next:NextFunction){try{return createdResponse(res,'Chat session created',await service.publicSession(publicSessionSchema.parse(req.body)));}catch(e){next(e);}}
export async function publicGet(req:AuthedRequest,res:Response,next:NextFunction){try{const result=await service.publicConversation(String(req.params.token));if(!result)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Chat session not found'}});return successResponse(res,'Chat session loaded',result);}catch(e){next(e);}}
export async function publicSend(req:AuthedRequest,res:Response,next:NextFunction){try{const result=await service.publicMessage(String(req.params.token),publicMessageSchema.parse(req.body));if(!result)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Chat session not found'}});return createdResponse(res,'Message received',result);}catch(e){next(e);}}
export async function adminList(req:AuthedRequest,res:Response,next:NextFunction){try{return successResponse(res,'Conversations loaded',await service.adminList({workspaceId:typeof req.query.workspaceId==='string'?req.query.workspaceId:undefined,status:typeof req.query.status==='string'?req.query.status:undefined,search:typeof req.query.search==='string'?req.query.search:undefined,limit:Number(req.query.limit)||100}));}catch(e){next(e);}}
export async function adminDetail(req:AuthedRequest,res:Response,next:NextFunction){try{const workspaceId=typeof req.query.workspaceId==='string'?req.query.workspaceId:'';const result=await import('./omnichannel.repo.js').then(m=>m.getConversation(workspaceId,String(req.params.conversationId)));if(!result)return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Conversation not found'}});return successResponse(res,'Conversation loaded',result);}catch(e){next(e);}}
export async function adminRouting(_req:AuthedRequest,res:Response,next:NextFunction){try{return successResponse(res,'Routing queue loaded',await service.adminRouting());}catch(e){next(e);}}
export async function adminResolve(req:AuthedRequest,res:Response,next:NextFunction){try{const input=adminResolveRoutingSchema.parse(req.body);return successResponse(res,'Routing item resolved',await service.adminResolve(String(req.params.routingId),input.workspaceId,uid(req),input.reason));}catch(e){next(e);}}
export async function adminChannels(_req:AuthedRequest,res:Response,next:NextFunction){try{return successResponse(res,'Channel health loaded',await import('./omnichannel.repo.js').then(m=>m.listChannels('__ADMIN__')));}catch(e){next(e);}}
export async function adminAnalytics(_req:AuthedRequest,res:Response,next:NextFunction){try{return successResponse(res,'Global OmniChannel analytics loaded',await import('../../db/pool.js').then(({query})=>query(`SELECT count(*)::int conversations,count(DISTINCT workspace_id)::int workspaces,count(*) FILTER(WHERE status IN ('OPEN','ACTIVE','ESCALATED'))::int active,count(*) FILTER(WHERE handling_mode IN ('AI_AUTO','AI_ASSISTED'))::int ai_handled,count(*) FILTER(WHERE handling_mode IN ('HUMAN','ESCALATED'))::int human_handled FROM omni_conversations`).then(r=>r.rows[0]??{})));}catch(e){next(e);}}
