import { forbiddenError, notFoundError } from '../../utils/app-error.js';
import { assertWorkspaceCapability } from '../workspaces/workspace-authorization.service.js';
import { query } from '../../db/pool.js';
import { recordSecurityEvent } from '../security/security-event.service.js';
import * as repo from './omnichannel.repo.js';

export async function assertWorkspace(workspaceId:string,userId:string,capability:'omnichannel.read'|'omnichannel.reply'|'omnichannel.manage') { await assertWorkspaceCapability({workspaceId,userId,capability}); }
export async function list(workspaceId:string,userId:string,filters:any){await assertWorkspace(workspaceId,userId,'omnichannel.read');return repo.listConversations(workspaceId,filters);}
export async function detail(workspaceId:string,id:string,userId:string){await assertWorkspace(workspaceId,userId,'omnichannel.read');const result=await repo.getConversation(workspaceId,id);if(!result)throw notFoundError('Conversation not found');return result;}
export async function send(workspaceId:string,id:string,userId:string,input:{text:string;messageType:string;clientMessageId?:string}) { await assertWorkspace(workspaceId,userId,'omnichannel.reply'); const result=await repo.getConversation(workspaceId,id);if(!result)throw notFoundError('Conversation not found'); if(result.conversation.status==='SPAM' || result.conversation.status==='CLOSED') throw forbiddenError('This conversation is not accepting messages'); if(result.conversation.handlingMode==='AI_AUTO') throw forbiddenError('Take over the conversation before sending as a human'); return repo.createMessage({workspaceId,conversationId:id,channelId:result.conversation.channelId,channelIdentityId:result.conversation.channelIdentityId,direction:'OUTBOUND',senderType:'USER',senderUserId:userId,messageType:input.messageType,text:input.text,...(input.clientMessageId ? {clientMessageId:input.clientMessageId} : {})},userId); }
export async function note(workspaceId:string,id:string,userId:string,text:string){await assertWorkspace(workspaceId,userId,'omnichannel.reply');const result=await repo.getConversation(workspaceId,id);if(!result)throw notFoundError('Conversation not found');return repo.createMessage({workspaceId,conversationId:id,channelId:result.conversation.channelId,channelIdentityId:result.conversation.channelIdentityId,direction:'INTERNAL',senderType:'USER',senderUserId:userId,messageType:'INTERNAL_NOTE',text},userId);}
export async function update(workspaceId:string,id:string,userId:string,input:any){await assertWorkspace(workspaceId,userId,'omnichannel.manage'); if(input.assignedUserId){const member=await query(`SELECT 1 FROM workspace_members WHERE workspace_id=$1 AND user_id=$2`,[workspaceId,input.assignedUserId]);if(!member.rows[0]) throw forbiddenError('Assigned user is not a workspace member');}const result=await repo.updateConversation(workspaceId,id,input,userId);if(!result)throw notFoundError('Conversation not found');return result;}
export async function channels(workspaceId:string,userId:string){await assertWorkspace(workspaceId,userId,'omnichannel.read');return repo.listChannels(workspaceId);}
export async function analytics(workspaceId:string,userId:string){await assertWorkspace(workspaceId,userId,'omnichannel.read');return repo.analytics(workspaceId);}
export async function createWebsite(workspaceId:string,userId:string,input:any){await assertWorkspace(workspaceId,userId,'omnichannel.manage');return repo.createWebsiteIdentity(workspaceId,input,userId);}
export async function takeOver(workspaceId:string,id:string,userId:string){return update(workspaceId,id,userId,{handlingMode:'HUMAN'});}
export async function returnToAi(workspaceId:string,id:string,userId:string,mode:'AI_AUTO'|'AI_ASSISTED'='AI_ASSISTED'){return update(workspaceId,id,userId,{handlingMode:mode});}
export async function publicSession(input:any){const result=await repo.createPublicSession(input.widgetId,input.origin,input.visitorId,input.pageContext);if(!result)throw notFoundError('Website chat widget not found or origin is not authorized');return result;}
export async function publicConversation(token:string){const session=await repo.getPublicSession(token);if(!session)return null;const result=await repo.getConversation(session.workspace_id,session.conversation_id);return result?{...result,workspaceId:undefined}:null;}
export async function publicMessage(token:string,input:any){const session=await repo.getPublicSession(token);if(!session)return null;const conversation=await repo.getConversation(session.workspace_id,session.conversation_id);if(!conversation)return null;return repo.createMessage({workspaceId:session.workspace_id,conversationId:session.conversation_id,channelId:conversation.conversation.channelId,channelIdentityId:conversation.conversation.channelIdentityId,direction:'INBOUND',senderType:'BUYER',messageType:input.messageType,text:input.text,clientMessageId:input.clientMessageId},null);}
export async function adminList(filters:any){return repo.listAdminConversations(filters);}
export async function adminRouting(){return repo.listRoutingQueue();}
export async function adminResolve(id:string,workspaceId:string,adminId:string,reason:string){const result=await repo.adminResolveRouting(id,workspaceId,adminId,reason);if(!result)throw notFoundError('Routing item not found');await recordSecurityEvent({eventType:'ADMIN_ACTION',userId:adminId,workspaceId,metadata:{action:'omnichannel.routing.resolve',targetId:id,reason}});return result;}
