import { conflictError, notFoundError } from '../../utils/app-error.js';
import * as repo from './product.repo.js';
import type { CreateProductInput, UpdateProductInput } from './product.validator.js';

export const listProducts = repo.listProducts;
export async function getProduct(workspaceId: string, productId: string) { const value = await repo.getProductDetail(workspaceId, productId); if (!value) throw notFoundError('Product not found'); return value; }
export async function createProduct(workspaceId: string, userId: string, input: CreateProductInput) { try { const id = await repo.createProduct(workspaceId,userId,input); return getProduct(workspaceId,id); } catch (error) { if ((error as {code?:string}).code === '23505') throw conflictError('A product with this SKU or internal code already exists'); throw error; } }
export async function updateProduct(workspaceId: string, productId: string, userId: string, input: UpdateProductInput) { try { if (!(await repo.updateProduct(workspaceId,productId,userId,input))) throw notFoundError('Product not found or version conflict'); return getProduct(workspaceId,productId); } catch (error) { if ((error as {code?:string}).code === '23505') throw conflictError('A product with this SKU or internal code already exists'); throw error; } }
export async function archiveProduct(workspaceId: string, productId: string, userId: string) { if (!(await repo.archiveProduct(workspaceId,productId,userId))) throw notFoundError('Product not found'); }
export async function listChildren(workspaceId: string, productId: string, key: repo.ChildKey) { if (!(await repo.findProduct(workspaceId,productId))) throw notFoundError('Product not found'); return repo.listChildren(workspaceId,productId,key); }
export async function createChild(workspaceId: string, productId: string, userId: string, key: repo.ChildKey, input: Record<string,unknown>) { if (!(await repo.findProduct(workspaceId,productId))) throw notFoundError('Product not found'); try { const id=await repo.createChild(workspaceId,productId,userId,key,input); return { id }; } catch (error) { if ((error as {code?:string}).code === '23505') throw conflictError('This product detail already exists'); throw error; } }
export async function deleteChild(workspaceId: string, productId: string, key: repo.ChildKey, childId: string) { if (!(await repo.deleteChild(workspaceId,productId,key,childId))) throw notFoundError('Product detail not found'); }
export async function createRelationship(workspaceId: string, productId: string, userId: string, input: { relatedProductId: string; relationshipType: string; notes?: string | null | undefined }) { if (!(await repo.findProduct(workspaceId,productId))) throw notFoundError('Product not found'); const id = await repo.createRelationship(workspaceId,productId,userId,input); if (!id) throw notFoundError('Related product not found'); return { id }; }
export async function deleteRelationship(workspaceId: string, productId: string, relationshipId: string) { if (!(await repo.deleteRelationship(workspaceId,productId,relationshipId))) throw notFoundError('Product relationship not found'); }
